// <auto-generated />
using System;
using Asp_projekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp_projekt.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507115052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asp_projekt.Models.Fakultet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fakulteti");
                });

            modelBuilder.Entity("Asp_projekt.Models.Izvjestaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojOcjena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumGeneriranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<double>("ProsjecnaOcjena")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Izvjestaji");
                });

            modelBuilder.Entity("Asp_projekt.Models.Kolegij", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<int?>("FakultetId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FakultetId");

                    b.ToTable("Kolegiji");
                });

            modelBuilder.Entity("Asp_projekt.Models.Ocjena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumOcjene")
                        .HasColumnType("datetime2");

                    b.Property<int>("KolegijId")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int>("Vrijednost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KolegijId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Ocjene");
                });

            modelBuilder.Entity("Asp_projekt.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FakultetId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Katedra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FakultetId");

                    b.ToTable("Profesori");
                });

            modelBuilder.Entity("Asp_projekt.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumUpisa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FakultetId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KolegijId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FakultetId");

                    b.HasIndex("KolegijId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("KolegijProfesor", b =>
                {
                    b.Property<int>("KolegijiId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesoriId")
                        .HasColumnType("int");

                    b.HasKey("KolegijiId", "ProfesoriId");

                    b.HasIndex("ProfesoriId");

                    b.ToTable("KolegijProfesor");
                });

            modelBuilder.Entity("Asp_projekt.Models.Izvjestaj", b =>
                {
                    b.HasOne("Asp_projekt.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Asp_projekt.Models.Kolegij", b =>
                {
                    b.HasOne("Asp_projekt.Models.Fakultet", "Fakultet")
                        .WithMany("Kolegiji")
                        .HasForeignKey("FakultetId");

                    b.Navigation("Fakultet");
                });

            modelBuilder.Entity("Asp_projekt.Models.Ocjena", b =>
                {
                    b.HasOne("Asp_projekt.Models.Kolegij", "Kolegij")
                        .WithMany()
                        .HasForeignKey("KolegijId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asp_projekt.Models.Profesor", "Profesor")
                        .WithMany("Ocjene")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asp_projekt.Models.Student", "Student")
                        .WithMany("DaneOcjene")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kolegij");

                    b.Navigation("Profesor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Asp_projekt.Models.Profesor", b =>
                {
                    b.HasOne("Asp_projekt.Models.Fakultet", "Fakultet")
                        .WithMany("Profesori")
                        .HasForeignKey("FakultetId");

                    b.Navigation("Fakultet");
                });

            modelBuilder.Entity("Asp_projekt.Models.Student", b =>
                {
                    b.HasOne("Asp_projekt.Models.Fakultet", "Fakultet")
                        .WithMany("Studenti")
                        .HasForeignKey("FakultetId");

                    b.HasOne("Asp_projekt.Models.Kolegij", null)
                        .WithMany("Studenti")
                        .HasForeignKey("KolegijId");

                    b.Navigation("Fakultet");
                });

            modelBuilder.Entity("KolegijProfesor", b =>
                {
                    b.HasOne("Asp_projekt.Models.Kolegij", null)
                        .WithMany()
                        .HasForeignKey("KolegijiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asp_projekt.Models.Profesor", null)
                        .WithMany()
                        .HasForeignKey("ProfesoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asp_projekt.Models.Fakultet", b =>
                {
                    b.Navigation("Kolegiji");

                    b.Navigation("Profesori");

                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("Asp_projekt.Models.Kolegij", b =>
                {
                    b.Navigation("Studenti");
                });

            modelBuilder.Entity("Asp_projekt.Models.Profesor", b =>
                {
                    b.Navigation("Ocjene");
                });

            modelBuilder.Entity("Asp_projekt.Models.Student", b =>
                {
                    b.Navigation("DaneOcjene");
                });
#pragma warning restore 612, 618
        }
    }
}
